// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRWTKo1CR4NxP4048Wd_cTzaoNTr4Gtc',
    appId: '1:939843715722:web:ec89468a29aa401842a373',
    messagingSenderId: '939843715722',
    projectId: 'social-media-app-bab63',
    authDomain: 'social-media-app-bab63.firebaseapp.com',
    storageBucket: 'social-media-app-bab63.appspot.com',
    measurementId: 'G-GF4KTBZQ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0XokEnZEbBQagSlQODaP0Ha_07iAOt1s',
    appId: '1:939843715722:android:4481aa772c2b791042a373',
    messagingSenderId: '939843715722',
    projectId: 'social-media-app-bab63',
    storageBucket: 'social-media-app-bab63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7rZs4aTVkX1qRYcVzM4Dc4ZxGGT4-sA',
    appId: '1:939843715722:ios:7babc8956b5f951842a373',
    messagingSenderId: '939843715722',
    projectId: 'social-media-app-bab63',
    storageBucket: 'social-media-app-bab63.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7rZs4aTVkX1qRYcVzM4Dc4ZxGGT4-sA',
    appId: '1:939843715722:ios:db13177b45c350e342a373',
    messagingSenderId: '939843715722',
    projectId: 'social-media-app-bab63',
    storageBucket: 'social-media-app-bab63.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
